### ISSUE TITLE
[Bug/Feature request] tokens with a hidden score banked can't be hear

### ISSUE THREAD

**Issue by TheXeno30** [Eligarf/stealthy#139] opened 2024-06-07 15:59 UTC
So.. usecase

I have token1 in the dark that another token2 can hear. If token1 hides then token2 can no long hear token1. all good.

If Token2 then spots token1 (aka. have a higher spot than token1s hide score) token 2 still can't hear token1.

hope it's clear :)

Also posted it on Vision5e HUB

**Comment by Eligarf** [comment] 2024-06-08 23:19
Pretty sure this is a vision5e issue. In v11, I see plenty of calls via the 'hearing' detection mode along with the others, but even though the other detection modes like 'light perception' or 'basic vision' work as expected, there are no calls to 'hearing' in V12 as far as I can tell. Are you running in Foundry V12?

**Comment by TheXeno30** [comment] 2024-06-09 14:28
Just talked to Vision5e and he/she/they (?) say it's might be on your side - something with not refreshing vision right. Not a programmer so have no idea :) 
Nope, not running V12 yet. Waiting for a lot of modules to level up :)

**Comment by Eligarf** [comment] 2024-06-10 16:06
I replied to your bug filed on Vision5e, TL;DR is I can't reproduce the behavior you are seeing. Are you by chance using the *Perceptive* module as well? I'll need a lot more information to be able to replicate the conditions leading to this problem.

**Comment by TheXeno30** [comment] 2024-06-10 20:50
Nah... have not installed Perceptive yet. Let me know what info you need from me. to start with i have these.
Foundr V11.315
DnD 3.2.0
Chrome Version 125.0.6422.142

Active Modules:
----------
Ace Library v;
Active Auras v;
Active Token Effects v;
Advanced Macros v;
Animated Dice Pack - TheRipper93 Premium Dice (Early Access) v;
Argon - Combat HUD (CORE) v;
Argon - Combat HUD (DND5E) v;
Arka Stream for Dice So Nice v;
Arms Reach v;
Automated Animations v;
Auto-Rotate v;
Baileywiki Mass Edit v;
Bar Brawl v;
Better Roll Tables v;
Better Roofs v;
Border Control v;
Break Time v;
Build-a-Bonus v;
Carousel Combat Tracker v;
Cayden's Dice v;
Chat Commander v;
Chat Images v;
Chris's Premades v;
Color Picker v;
Combat Booster: Turn Marker, Recent Actions and more v;
Compact Scene Navigation v;
Compendium Folders v;
D&D5e Animations v;
Designer Doors v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice So Nice - Weighted Companion Cube Dice Set v;
Dice Tray v;
DnDshared (Shared Compendiums) v;
Downtime (Dnd5e) v;
Drag Ruler v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects (DAE) v;
Effect Macro v;
Epic Rolls 5e v;
Falemos (let's talk) v;
Filepicker + v;
Find the Culprit v;
Foundry VTT Anniversary Dice Set by The Rollsmith v;
FXMaster v;
Gambit's Premades v;
Gatherer v;
Handyfon's Dice Addiction v;
Hey, Wait! v;
Hover Distance v;
Image Context v;
Inactive Tokens v;
Item Macro v;
Item Piles v;
Jack Kerouac's Animated Spell Effects v;
JB2A - Patreon Complete Collection v;
Jinker's Animated Art Pack v;
Levels v;
Levels - Automatic Cover Calculator v;
Levels - Volumetric Templates v;
lib - Color Settings v;
Library: Scene Packer v;
libWrapper v;
LiveKit AVClient v;
Lordu's Custom Dice for Dice So Nice v;
Mastercrafted - Crafting Manager v;
Material Components v;
Maxwell's Manual of Malicious Maladies v;
Midi QOL v;
Midi SRD v;
Minimal UI v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Hotbar Expansion v;
Monk's Little Details v;
Monk's Player Settings v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
More SFX Triggers for Dice So Nice v;
Moulinette Compendiums (module) v;
Moulinette Core v;
Moulinette Game Icons (module) v;
Moulinette Image Search (module) v;
Moulinette Scenes (module) v;
Moulinette Tiles (module) v;
Phandelver & Below: The Shattered Obelisk v;
Plutonium v;
Plutonium Addon: Automation v;
Point of Interest Teleporter v;
PopOut! v;
Potion Crafting & Gathering v;
Puzzle Locks v;
Quick Insert - Search Widget v;
QuickScale v;
Rideable v;
routinglib v;
Select tool everywhere v;
Sequencer v;
Show Token Art v;
Simple Calendar v;
Simple Quest v;
SmallTime v;
Smart Doors v;
Smart Target v;
socketlib v;
Splatter v;
Spotlight Omnisearch v;
Stealthy v;
Syrinscape Control v;
Tagger v;
Talis Dice v;
Template Macro v;
The Forge v;
The Forge: More Awesomeness v;
TheRipper93's Module Hub v;
The Rollsmith - A House Divided Dice Set v;
The Rollsmith - Black Marble Dice Set v;
The Rollsmith - Dragon Drogon Dice Set v;
The Rollsmith - Gold Ore Dice Set v;
The Rollsmith - Iridescent Rainbow Dice Set v;
The Rollsmith - Ruby Dice Set v;
Tidbits v;
Tidy UI - Game Settings v;
Tile Scroll v;
Tile Sort v;
Times Up v;
Token Attacher v;
Token Elevator v;
Token Magic FX v;
Token Variant Art v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
Warp Gate v;
Wave Dice - TheRipper93 Premium Dice (Supporter) v;
WikiRole for Dice So Nice v;
WTF: What the Flag? v;

Inactive Modules:
----------
About Time v;
CotO Addons v;
Crown of the Oathbreaker v;
Items with Spells DnD5e v;
Macro Editor v;
Perceptive v;
Power Select Toolkit v;

**Comment by Eligarf** [comment] 2024-06-16 15:37
Based on the vision-5e bug comments I'm going to close this

**Closed as completed by Eligarf** 2024-06-16 15:37 UTC
