### ISSUE TITLE
[BUG] Walls stealth field not showing then using other wall enchancing modules

### ISSUE THREAD

**Issue by TheXeno30** [Eligarf/stealthy#140] opened 2024-06-07 16:02 UTC
Walls stealth field not showing then using other wall enchancing modules - like enhanced walls, levels, arms reach and many more :)

suggestion to move it into a tab on the walled config page. Getting crowded :)

**Comment by Eligarf** [comment] 2024-06-10 16:10
Like before, I cannot reproduce this bug you are having. Please tell me all the active modules you are using (Tidy UI has an easy button to export all the modules and versions).

**Comment by TheXeno30** [comment] 2024-06-10 20:47
Here you go :) 
hope it help. I know there is a lot of modules
-----
Active Modules:
----------
Ace Library v;
Active Auras v;
Active Token Effects v;
Advanced Macros v;
Animated Dice Pack - TheRipper93 Premium Dice (Early Access) v;
Argon - Combat HUD (CORE) v;
Argon - Combat HUD (DND5E) v;
Arka Stream for Dice So Nice v;
Arms Reach v;
Automated Animations v;
Auto-Rotate v;
Baileywiki Mass Edit v;
Bar Brawl v;
Better Roll Tables v;
Better Roofs v;
Border Control v;
Break Time v;
Build-a-Bonus v;
Carousel Combat Tracker v;
Cayden's Dice v;
Chat Commander v;
Chat Images v;
Chris's Premades v;
Color Picker v;
Combat Booster: Turn Marker, Recent Actions and more v;
Compact Scene Navigation v;
Compendium Folders v;
D&D5e Animations v;
Designer Doors v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice So Nice - Weighted Companion Cube Dice Set v;
Dice Tray v;
DnDshared (Shared Compendiums) v;
Downtime (Dnd5e) v;
Drag Ruler v;
Dynamic Active Effects SRD v;
Dynamic effects using Active Effects (DAE) v;
Effect Macro v;
Epic Rolls 5e v;
Falemos (let's talk) v;
Filepicker + v;
Find the Culprit v;
Foundry VTT Anniversary Dice Set by The Rollsmith v;
FXMaster v;
Gambit's Premades v;
Gatherer v;
Handyfon's Dice Addiction v;
Hey, Wait! v;
Hover Distance v;
Image Context v;
Inactive Tokens v;
Item Macro v;
Item Piles v;
Jack Kerouac's Animated Spell Effects v;
JB2A - Patreon Complete Collection v;
Jinker's Animated Art Pack v;
Levels v;
Levels - Automatic Cover Calculator v;
Levels - Volumetric Templates v;
lib - Color Settings v;
Library: Scene Packer v;
libWrapper v;
LiveKit AVClient v;
Lordu's Custom Dice for Dice So Nice v;
Mastercrafted - Crafting Manager v;
Material Components v;
Maxwell's Manual of Malicious Maladies v;
Midi QOL v;
Midi SRD v;
Minimal UI v;
Monk's Active Tile Triggers v;
Monk's Bloodsplats v;
Monk's Combat Details v;
Monk's Enhanced Journal v;
Monk's Hotbar Expansion v;
Monk's Little Details v;
Monk's Player Settings v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
More SFX Triggers for Dice So Nice v;
Moulinette Compendiums (module) v;
Moulinette Core v;
Moulinette Game Icons (module) v;
Moulinette Image Search (module) v;
Moulinette Scenes (module) v;
Moulinette Tiles (module) v;
Phandelver & Below: The Shattered Obelisk v;
Plutonium v;
Plutonium Addon: Automation v;
Point of Interest Teleporter v;
PopOut! v;
Potion Crafting & Gathering v;
Puzzle Locks v;
Quick Insert - Search Widget v;
QuickScale v;
Rideable v;
routinglib v;
Select tool everywhere v;
Sequencer v;
Show Token Art v;
Simple Calendar v;
Simple Quest v;
SmallTime v;
Smart Doors v;
Smart Target v;
socketlib v;
Splatter v;
Spotlight Omnisearch v;
Stealthy v;
Syrinscape Control v;
Tagger v;
Talis Dice v;
Template Macro v;
The Forge v;
The Forge: More Awesomeness v;
TheRipper93's Module Hub v;
The Rollsmith - A House Divided Dice Set v;
The Rollsmith - Black Marble Dice Set v;
The Rollsmith - Dragon Drogon Dice Set v;
The Rollsmith - Gold Ore Dice Set v;
The Rollsmith - Iridescent Rainbow Dice Set v;
The Rollsmith - Ruby Dice Set v;
Tidbits v;
Tidy UI - Game Settings v;
Tile Scroll v;
Tile Sort v;
Times Up v;
Token Attacher v;
Token Elevator v;
Token Magic FX v;
Token Variant Art v;
Vision 5e v;
Visual Active Effects v;
Walled Templates v;
Wall Height v;
Warp Gate v;
Wave Dice - TheRipper93 Premium Dice (Supporter) v;
WikiRole for Dice So Nice v;
WTF: What the Flag? v;

Inactive Modules:
----------
About Time v;
CotO Addons v;
Crown of the Oathbreaker v;
Items with Spells DnD5e v;
Macro Editor v;
Perceptive v;
Power Select Toolkit v;

**Comment by TheXeno30** [comment] 2024-06-11 06:31
It seem it was a glitch at me side. I had to uninstall both stealthy and perceptive completely (was installed but not an active module) and install it again - then the stealth wall showed up. Vere odd, but probably the way it is with a lot of modules.

**Comment by Eligarf** [comment] 2024-06-11 14:22
I'm going to close this for now, thanks for letting me know of the glitch.

**Closed as not planned** 2024-06-11 14:23 UTC
